### ISSUE TITLE
Controller 추가

### ISSUE THREAD

**Issue by Hyeondoonge** [woowa-techcamp-2022/web-moneybook-1#21]
## 작업
- [x] 현재 프로젝트 구조(Model-View)에서 Controller를 추가해서 분리합니다.
  - controller 작성 시, 커버할 범위(ex. 페이지 별로 또는 모든 페이지의 서비스를 갖고있는 컨트롤러)를 결정해야합니다.

## 참고사항
❌

## 예상 소요기간
(예상 소요시간을 기록해주세요!)

**Comment by kms-97** [comment]
향후 state를 아래와 같은 형식으로 관리하고자 합니다.
KEY = VALUE
current_date = {year: number, month: number};
current_history = [{date:number, data:[{id: number, content: string, categoryId: number, paymentId: number, amount: number, isIncome: boolean}]}]
last_six_month_history = [{year: number, month: number, data:current_history}]
category = [{id: number, content: string, isIncome: boolean, color: string}]
payment = [{id: number, content: string}]
selected_history = {year: number, month: number, date: number, id: number, content: string, categoryId: number, paymentId: number, amount: number: isIncome: boolean}
